### PR TITLE
Add Ubuntu 14.04 and RHEL 7 support

### PR DESCRIPTION
**Pull request by ryancragun**
* Add Ubuntu 14.04 support
* Add initial RHEL 7 support
* Update embedded Ruby to 2.2.3
* Update embedded Rubygems to 2.4.8
* Update embedded Chef gem to use git master
* Update omnibus, omnibus-ctl and omnibus-software to use git master

### CODE REVIEW

**Comment by ryancragun** [comment]
http://wilson.ci.chef.co/job/chef-marketplace-trigger-ad_hoc/9/downstreambuildview/

**Comment by ryancragun** [comment]
http://wilson.ci.chef.co/job/chef-marketplace-trigger-ad_hoc/10/downstreambuildview/

**Comment by jjasghar** [comment]
:+1: :rocket: :cake: :+1:

**Comment by adamleff** [comment]
LGTM :+1:

**Pull request merged**
